//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SampleEntityFrameWork
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int Id { get; set; }
        public string Make { get; set; }
        public string Color { get; set; }
        public string PetName { get; set; }

        public override string ToString()
        {
            return String.Format("{0} is {1},{2} with ID={3}", this.Make ?? "No Name", this.Color, this.PetName,this.Id);
        }

        //partial void OnInventoryMakeChanging(String value)
        //{
        //    Console.WriteLine("\t-> Changing make to :{0}",value);
        //}

        //partial void OnMakeNameChanged()
        //{
        //    Console.WriteLine("\t-> Make of inventory has been changed!");
        //}

    }
}
